// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5howzuPiGrIJwz-6Kxhz1eXYPiTC4iqM',
    appId: '1:21709533185:web:4414ba052aa2a103841000',
    messagingSenderId: '21709533185',
    projectId: 'readspace-library',
    authDomain: 'readspace-library.firebaseapp.com',
    storageBucket: 'readspace-library.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jpe-5ru_tIezCNgydCkK1iJiTNuulPc',
    appId: '1:21709533185:android:0381dfab06fbca9c841000',
    messagingSenderId: '21709533185',
    projectId: 'readspace-library',
    storageBucket: 'readspace-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAePQrJJX2ORFkViynVugWLsX6r5Pcm5ow',
    appId: '1:21709533185:ios:77c31ad1e3711fb5841000',
    messagingSenderId: '21709533185',
    projectId: 'readspace-library',
    storageBucket: 'readspace-library.firebasestorage.app',
    iosBundleId: 'com.example.readspaceStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAePQrJJX2ORFkViynVugWLsX6r5Pcm5ow',
    appId: '1:21709533185:ios:77c31ad1e3711fb5841000',
    messagingSenderId: '21709533185',
    projectId: 'readspace-library',
    storageBucket: 'readspace-library.firebasestorage.app',
    iosBundleId: 'com.example.readspaceStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5howzuPiGrIJwz-6Kxhz1eXYPiTC4iqM',
    appId: '1:21709533185:web:34a991410aba35cb841000',
    messagingSenderId: '21709533185',
    projectId: 'readspace-library',
    authDomain: 'readspace-library.firebaseapp.com',
    storageBucket: 'readspace-library.firebasestorage.app',
  );
}
